const baseUrl = (process.env.NEXT_PUBLIC_SITE_URL || "").replace(/\/$/, "");

/** @type {import('next-sitemap').IConfig} */
const config = {
  siteUrl: baseUrl || "http://localhost:3000",
  generateRobotsTxt: true,
  generateIndexSitemap: false,
  outDir: "public",
  autoLastmod: true,
  exclude: ["/api*", "/_blog*", "/404", "/500", "/not-found"],
  robotsTxtOptions: {
    policies: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/_blog",
          "/customers",
          "/demos",
          "/privacy-policy",
          "/resources",
          "/web-rtc",
          "/author/developer",
          "/who-we-are",
          "/blog",
        ],
      },
      // {
      //   userAgent: "Googlebot",
      //   allow: "/",
      //   disallow: ["/api", "/_blog"],
      // },
    ],
    additionalSitemaps: baseUrl
      ? [`${baseUrl}/sitemap-services.xml`, `${baseUrl}/sitemap-industries.xml`]
      : [],
    includeNonIndexSitemaps: true,
    transformRobotsTxt: async (config, robotsTxt) => {
      // Example: append custom comment to robots.txt
      return robotsTxt + "\n# Generated by next-sitemap";
    },
  },

  transform: async (config, path) => {
    const cleanPath = path === "" ? "/" : path;
    const isRoot = cleanPath === "/";
    const isMain = ["/about-us", "/contact", "/terms-and-conditions"].includes(
      cleanPath,
    );
    const isServicesRoot = cleanPath === "/services";
    const isIndustriesRoot = cleanPath === "/industries";
    const isServicesChild =
      cleanPath.startsWith("/services/") && cleanPath !== "/services";
    const isIndustriesChild =
      cleanPath.startsWith("/industries/") && cleanPath !== "/industries";

    // Skip excluded paths
    if (
      config.exclude?.some((pattern) =>
        cleanPath.startsWith(pattern.replace("*", "")),
      )
    ) {
      return null;
    }

    // Include only wanted paths
    const include =
      isRoot ||
      isMain ||
      isServicesRoot ||
      isIndustriesRoot ||
      isServicesChild ||
      isIndustriesChild;

    if (!include) return null;

    return {
      loc: cleanPath,
      changefreq: isRoot ? "weekly" : "monthly",
      priority: isRoot
        ? 1.0
        : isMain
          ? 1.0
          : isServicesRoot || isServicesChild
            ? 0.9
            : 0.8,
    };
  },
};

export default config;
